name: Lint

on: [push, pull_request]

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - id: nodeversion
        run: echo "version=$(grep nodejs .tool-versions | sed -e 's/[^[:space:]]*[[:space:]]*//')" >> $GITHUB_OUTPUT
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.nodeversion.outputs.version }}
          cache: yarn
      - name: Install dependencies
        run: yarn install --immutable
      - name: Run linters
        uses: wearerequired/lint-action@v1
        with:
          github_token: ${{ secrets.github_token }}
          prettier: true
          auto_fix: true
